"""data_model_v2

Revision ID: 62a54b62ed20
Revises: c1a2b3c4d5e6

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62a54b62ed20"
down_revision: Union[str, None] = "c1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("serial_number", sa.String(length=100), nullable=False),
        sa.Column("provider_name", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "device_software",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("data_point_series", sa.Column("external_id", sa.String(length=100), nullable=True))
    op.add_column("data_point_series", sa.Column("external_device_mapping_id", sa.UUID(), nullable=False))
    op.add_column("data_point_series", sa.Column("series_type_definition_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("idx_data_point_series_mapping_type_time"), table_name="data_point_series")
    op.create_index(
        "idx_data_point_series_mapping_type_time",
        "data_point_series",
        ["external_device_mapping_id", "series_type_definition_id", "recorded_at"],
        unique=False,
    )
    op.drop_constraint(op.f("data_point_series_external_mapping_id_fkey"), "data_point_series", type_="foreignkey")
    op.drop_constraint(op.f("data_point_series_series_type_id_fkey"), "data_point_series", type_="foreignkey")
    op.create_foreign_key(
        None,
        "data_point_series",
        "external_device_mapping",
        ["external_device_mapping_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "data_point_series",
        "series_type_definition",
        ["series_type_definition_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("data_point_series", "external_mapping_id")
    op.drop_column("data_point_series", "series_type_id")
    op.add_column("event_record", sa.Column("external_id", sa.String(length=100), nullable=True))
    op.add_column("event_record", sa.Column("external_device_mapping_id", sa.UUID(), nullable=False))
    op.drop_constraint(op.f("uq_event_record_datetime_category"), "event_record", type_="unique")
    op.drop_index(op.f("idx_event_record_mapping_category"), table_name="event_record")
    op.create_index(
        "idx_event_record_mapping_category",
        "event_record",
        ["external_device_mapping_id", "category"],
        unique=False,
    )
    op.drop_index(op.f("idx_event_record_mapping_time"), table_name="event_record")
    op.create_index(
        "idx_event_record_mapping_time",
        "event_record",
        ["external_device_mapping_id", "start_datetime", "end_datetime"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_event_record_datetime",
        "event_record",
        ["external_device_mapping_id", "start_datetime", "end_datetime"],
    )
    op.drop_constraint(op.f("event_record_external_mapping_id_fkey"), "event_record", type_="foreignkey")
    op.create_foreign_key(
        None,
        "event_record",
        "external_device_mapping",
        ["external_device_mapping_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("event_record", "external_mapping_id")
    op.add_column("external_device_mapping", sa.Column("provider_name", sa.String(length=10), nullable=False))
    op.drop_constraint(op.f("uq_external_mapping_user_provider_device"), "external_device_mapping", type_="unique")
    op.create_unique_constraint(
        "uq_external_mapping_user_provider_device",
        "external_device_mapping",
        ["user_id", "provider_name", "device_id"],
    )
    op.drop_column("external_device_mapping", "provider_id")
    op.alter_column(
        "series_type_definition",
        "code",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.add_column("sleep_details", sa.Column("is_nap", sa.Boolean(), nullable=True))
    op.add_column("workout_details", sa.Column("energy_burned", sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column("workout_details", sa.Column("distance", sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column("workout_details", sa.Column("steps_count", sa.Integer(), nullable=True))
    op.drop_column("workout_details", "steps_max")
    op.drop_column("workout_details", "steps_avg")
    op.drop_column("workout_details", "steps_total")
    op.drop_column("workout_details", "steps_min")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workout_details", sa.Column("steps_min", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("workout_details", sa.Column("steps_total", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "workout_details",
        sa.Column("steps_avg", sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    )
    op.add_column("workout_details", sa.Column("steps_max", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column("workout_details", "steps_count")
    op.drop_column("workout_details", "distance")
    op.drop_column("workout_details", "energy_burned")
    op.drop_column("sleep_details", "is_nap")
    op.alter_column(
        "series_type_definition",
        "code",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.add_column(
        "external_device_mapping",
        sa.Column("provider_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.drop_constraint("uq_external_mapping_user_provider_device", "external_device_mapping", type_="unique")
    op.create_unique_constraint(
        op.f("uq_external_mapping_user_provider_device"),
        "external_device_mapping",
        ["user_id", "provider_id", "device_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("external_device_mapping", "provider_name")
    op.add_column("event_record", sa.Column("external_mapping_id", sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "event_record", type_="foreignkey")
    op.create_foreign_key(
        op.f("event_record_external_mapping_id_fkey"),
        "event_record",
        "external_device_mapping",
        ["external_mapping_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_event_record_datetime", "event_record", type_="unique")
    op.drop_index("idx_event_record_mapping_time", table_name="event_record")
    op.create_index(
        op.f("idx_event_record_mapping_time"),
        "event_record",
        ["external_mapping_id", "start_datetime", "end_datetime"],
        unique=False,
    )
    op.drop_index("idx_event_record_mapping_category", table_name="event_record")
    op.create_index(
        op.f("idx_event_record_mapping_category"),
        "event_record",
        ["external_mapping_id", "category"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_event_record_datetime_category"),
        "event_record",
        ["external_mapping_id", "start_datetime", "category"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("event_record", "external_device_mapping_id")
    op.drop_column("event_record", "external_id")
    op.add_column("data_point_series", sa.Column("series_type_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("data_point_series", sa.Column("external_mapping_id", sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "data_point_series", type_="foreignkey")
    op.drop_constraint(None, "data_point_series", type_="foreignkey")
    op.create_foreign_key(
        op.f("data_point_series_series_type_id_fkey"),
        "data_point_series",
        "series_type_definition",
        ["series_type_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("data_point_series_external_mapping_id_fkey"),
        "data_point_series",
        "external_device_mapping",
        ["external_mapping_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("idx_data_point_series_mapping_type_time", table_name="data_point_series")
    op.create_index(
        op.f("idx_data_point_series_mapping_type_time"),
        "data_point_series",
        ["external_mapping_id", "series_type_id", "recorded_at"],
        unique=False,
    )
    op.drop_column("data_point_series", "series_type_definition_id")
    op.drop_column("data_point_series", "external_device_mapping_id")
    op.drop_column("data_point_series", "external_id")
    op.drop_table("device_software")
    op.drop_table("device")
    # ### end Alembic commands ###
