"""add_application_table

Revision ID: 218666d94c82
Revises: 62a54b62ed20

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "218666d94c82"
down_revision: Union[str, None] = "62a54b62ed20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.String(length=64), nullable=False),
        sa.Column("app_secret_hash", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("developer_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["developer_id"], ["developer.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_id"),
    )
    op.drop_index(op.f("ix_invitation_email_status"), table_name="invitation")
    op.drop_index(op.f("ix_invitation_token"), table_name="invitation")
    op.create_unique_constraint(None, "invitation", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invitation", type_="unique")
    op.create_index(op.f("ix_invitation_token"), "invitation", ["token"], unique=True)
    op.create_index(op.f("ix_invitation_email_status"), "invitation", ["email", "status"], unique=False)
    op.drop_table("application")
    # ### end Alembic commands ###
