"""data model v1

Revision ID: bbfb683a7c6c
Revises: bb5425bd11d0

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbfb683a7c6c"
down_revision: Union[str, None] = "bb5425bd11d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "series_type_definition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "external_device_mapping",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=True),
        sa.Column("device_id", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider_id", "device_id", name="uq_external_mapping_user_provider_device"),
    )
    op.create_index("idx_external_mapping_device", "external_device_mapping", ["device_id"], unique=False)
    op.create_index("idx_external_mapping_user", "external_device_mapping", ["user_id"], unique=False)
    op.create_table(
        "personal_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("sex", sa.Boolean(), nullable=True),
        sa.Column("gender", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "data_point_series",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_mapping_id", sa.UUID(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("series_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["external_mapping_id"], ["external_device_mapping.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_type_id"], ["series_type_definition.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_data_point_series_mapping_type_time",
        "data_point_series",
        ["external_mapping_id", "series_type_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "event_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_mapping_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=True),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("start_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["external_mapping_id"], ["external_device_mapping.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "external_mapping_id",
            "start_datetime",
            "category",
            name="uq_event_record_datetime_category",
        ),
    )
    op.create_index(
        "idx_event_record_mapping_category",
        "event_record",
        ["external_mapping_id", "category"],
        unique=False,
    )
    op.create_index(
        "idx_event_record_mapping_time",
        "event_record",
        ["external_mapping_id", "start_datetime", "end_datetime"],
        unique=False,
    )
    op.create_table(
        "event_record_detail",
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("detail_type", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["record_id"], ["event_record.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_table(
        "sleep_details",
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("sleep_total_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("sleep_time_in_bed_minutes", sa.Integer(), nullable=True),
        sa.Column("sleep_efficiency_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("sleep_deep_minutes", sa.Integer(), nullable=True),
        sa.Column("sleep_rem_minutes", sa.Integer(), nullable=True),
        sa.Column("sleep_light_minutes", sa.Integer(), nullable=True),
        sa.Column("sleep_awake_minutes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["record_id"], ["event_record_detail.record_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_table(
        "workout_details",
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("heart_rate_min", sa.Integer(), nullable=True),
        sa.Column("heart_rate_max", sa.Integer(), nullable=True),
        sa.Column("heart_rate_avg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("steps_min", sa.Integer(), nullable=True),
        sa.Column("steps_max", sa.Integer(), nullable=True),
        sa.Column("steps_avg", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("steps_total", sa.Integer(), nullable=True),
        sa.Column("max_speed", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("max_watts", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("moving_time_seconds", sa.Integer(), nullable=True),
        sa.Column("total_elevation_gain", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("average_speed", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("average_watts", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("elev_high", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("elev_low", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.ForeignKeyConstraint(["record_id"], ["event_record_detail.record_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("record_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workout_details")
    op.drop_table("sleep_details")
    op.drop_table("event_record_detail")
    op.drop_index("idx_event_record_mapping_time", table_name="event_record")
    op.drop_index("idx_event_record_mapping_category", table_name="event_record")
    op.drop_table("event_record")
    op.drop_index("idx_data_point_series_mapping_type_time", table_name="data_point_series")
    op.drop_table("data_point_series")
    op.drop_table("personal_record")
    op.drop_index("idx_external_mapping_user", table_name="external_device_mapping")
    op.drop_index("idx_external_mapping_device", table_name="external_device_mapping")
    op.drop_table("external_device_mapping")
    op.drop_table("series_type_definition")
    # ### end Alembic commands ###
