"""archive

Revision ID: cd18aa553afd
Revises: 07afc893962c

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd18aa553afd"
down_revision: Union[str, None] = "07afc893962c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archival_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("archive_after_days", sa.Integer(), nullable=True),
        sa.Column("delete_after_days", sa.Integer(), nullable=True),
        sa.CheckConstraint("id = 1", name="ck_archival_settings_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_point_series_archive",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("data_source_id", sa.UUID(), nullable=False),
        sa.Column("series_type_definition_id", sa.Integer(), nullable=False),
        sa.Column("bucket_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("aggregation_type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_source.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_type_definition_id"], ["series_type_definition.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "data_source_id",
            "series_type_definition_id",
            "bucket_start_at",
            "aggregation_type",
            name="uq_archive_source_type_start_agg",
        ),
    )
    op.drop_index(op.f("idx_data_point_series_source_type_time"), table_name="data_point_series")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_data_point_series_source_type_time"),
        "data_point_series",
        ["data_source_id", "series_type_definition_id", "recorded_at"],
        unique=False,
    )
    op.drop_table("data_point_series_archive")
    op.drop_table("archival_settings")
    # ### end Alembic commands ###
