"""timezone_offset

Revision ID: f99ae82f0470
Revises: 6c79a39350f4

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f99ae82f0470"
down_revision: Union[str, None] = "6c79a39350f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_point_series", sa.Column("zone_offset", sa.String(length=10), nullable=True))
    op.add_column("event_record", sa.Column("zone_offset", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_record", "zone_offset")
    op.drop_column("data_point_series", "zone_offset")
    # ### end Alembic commands ###
