"""timeseries unique constraint

Revision ID: 7a36d24b6c9c
Revises: 218666d94c82

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a36d24b6c9c"
down_revision: Union[str, None] = "218666d94c82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_data_point_series_mapping_type_time",
        "data_point_series",
        ["external_device_mapping_id", "series_type_definition_id", "recorded_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_data_point_series_mapping_type_time", "data_point_series", type_="unique")
    # ### end Alembic commands ###
