"""health score reindex

Revision ID: cdac07b15b04
Revises: 5643d2210b58

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdac07b15b04"
down_revision: Union[str, None] = "5643d2210b58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("health_score", sa.Column("user_id", sa.UUID(), nullable=False))
    op.alter_column("health_score", "provider", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.drop_constraint(op.f("uq_health_score_source_category_time"), "health_score", type_="unique")
    op.create_unique_constraint(
        "uq_health_score_user_provider_category_time",
        "health_score",
        ["user_id", "provider", "category", "recorded_at"],
    )
    op.create_foreign_key(None, "health_score", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "health_score", type_="foreignkey")
    op.drop_constraint("uq_health_score_user_provider_category_time", "health_score", type_="unique")
    op.create_unique_constraint(
        op.f("uq_health_score_source_category_time"),
        "health_score",
        ["data_source_id", "category", "recorded_at"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column("health_score", "provider", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.drop_column("health_score", "user_id")
    # ### end Alembic commands ###
