"""clear internal sleep scores

Revision ID: cc39513098b0
Revises: cdac07b15b04

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc39513098b0"
down_revision: Union[str, None] = "cdac07b15b04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("health_score", sa.Column("sleep_record_id", sa.UUID(), nullable=True))
    op.create_index(
        "uq_health_score_sleep_record",
        "health_score",
        ["sleep_record_id"],
        unique=True,
        postgresql_where=sa.text("sleep_record_id IS NOT NULL"),
    )
    op.create_foreign_key(None, "health_score", "event_record", ["sleep_record_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###
    op.execute(
        "DELETE FROM health_score WHERE provider = 'internal' AND category = 'sleep' AND sleep_record_id IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "health_score", type_="foreignkey")
    op.drop_index(
        "uq_health_score_sleep_record",
        table_name="health_score",
        postgresql_where=sa.text("sleep_record_id IS NOT NULL"),
    )
    op.drop_column("health_score", "sleep_record_id")
    # ### end Alembic commands ###
