"""sleep_stages

Revision ID: 07afc893962c
Revises: 31c7f45b636f

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "07afc893962c"
down_revision: Union[str, None] = "31c7f45b636f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_refresh_token_developer_id"), table_name="refresh_token")
    op.drop_index(op.f("idx_refresh_token_user_id"), table_name="refresh_token")
    op.add_column("sleep_details", sa.Column("sleep_stages", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(
        "ix_sleep_details_stages_gin",
        "sleep_details",
        ["sleep_stages"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"sleep_stages": "jsonb_path_ops"},
    )
    op.drop_index(op.f("idx_user_invitation_code_user_id"), table_name="user_invitation_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_user_invitation_code_user_id"), "user_invitation_code", ["user_id"], unique=False)
    op.drop_index(
        "ix_sleep_details_stages_gin",
        table_name="sleep_details",
        postgresql_using="gin",
        postgresql_ops={"sleep_stages": "jsonb_path_ops"},
    )
    op.drop_column("sleep_details", "sleep_stages")
    op.create_index(op.f("idx_refresh_token_user_id"), "refresh_token", ["user_id"], unique=False)
    op.create_index(op.f("idx_refresh_token_developer_id"), "refresh_token", ["developer_id"], unique=False)
    # ### end Alembic commands ###
