"""live_sync_mode

Revision ID: 1f0831f5831e
Revises: cc39513098b0

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f0831f5831e"
down_revision: Union[str, None] = "cc39513098b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provider_settings", sa.Column("live_sync_mode", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider_settings", "live_sync_mode")
    # ### end Alembic commands ###
