"""index_renaming

Revision ID: 6c79a39350f4
Revises: cd18aa553afd

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c79a39350f4"
down_revision: Union[str, None] = "cd18aa553afd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_data_point_series_archive_bucket_start_at"),
        "data_point_series_archive",
        ["bucket_start_at"],
        unique=False,
    )
    op.drop_index(op.f("idx_data_source_user_provider"), table_name="data_source")
    op.create_index("ix_data_source_user_provider", "data_source", ["user_id", "provider"], unique=False)
    op.drop_index(op.f("idx_device_type_priority_order"), table_name="device_type_priority")
    op.create_index(op.f("ix_device_type_priority_priority"), "device_type_priority", ["priority"], unique=False)
    op.drop_index(op.f("idx_event_record_source_category"), table_name="event_record")
    op.drop_index(op.f("idx_event_record_source_time"), table_name="event_record")
    op.drop_constraint(op.f("uq_event_record_datetime"), "event_record", type_="unique")
    op.create_index("ix_event_record_source_category", "event_record", ["data_source_id", "category"], unique=False)
    op.create_index(
        "ix_event_record_source_time", "event_record", ["data_source_id", "start_datetime", "end_datetime"], unique=True
    )
    op.drop_index(op.f("idx_provider_priority_order"), table_name="provider_priority")
    op.create_index(op.f("ix_provider_priority_priority"), "provider_priority", ["priority"], unique=False)
    op.create_index(op.f("ix_refresh_token_developer_id"), "refresh_token", ["developer_id"], unique=False)
    op.create_index(op.f("ix_refresh_token_user_id"), "refresh_token", ["user_id"], unique=False)
    op.drop_index(
        op.f("idx_user_connection_token_expiry"),
        table_name="user_connection",
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.drop_index(op.f("idx_user_connection_user_provider"), table_name="user_connection")
    op.drop_constraint(op.f("uq_user_provider"), "user_connection", type_="unique")
    op.create_index(
        "ix_user_connection_token_expiry",
        "user_connection",
        ["token_expires_at"],
        unique=False,
        postgresql_where="status = 'active'",
    )
    op.create_index("ix_user_connection_user_provider", "user_connection", ["user_id", "provider"], unique=True)
    op.create_index(op.f("ix_user_invitation_code_user_id"), "user_invitation_code", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_invitation_code_user_id"), table_name="user_invitation_code")
    op.drop_index("ix_user_connection_user_provider", table_name="user_connection")
    op.drop_index("ix_user_connection_token_expiry", table_name="user_connection", postgresql_where="status = 'active'")
    op.create_unique_constraint(
        op.f("uq_user_provider"), "user_connection", ["user_id", "provider"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_user_connection_user_provider"), "user_connection", ["user_id", "provider"], unique=False)
    op.create_index(
        op.f("idx_user_connection_token_expiry"),
        "user_connection",
        ["token_expires_at"],
        unique=False,
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.drop_index(op.f("ix_refresh_token_user_id"), table_name="refresh_token")
    op.drop_index(op.f("ix_refresh_token_developer_id"), table_name="refresh_token")
    op.drop_index(op.f("ix_provider_priority_priority"), table_name="provider_priority")
    op.create_index(op.f("idx_provider_priority_order"), "provider_priority", ["priority"], unique=False)
    op.drop_index("ix_event_record_source_time", table_name="event_record")
    op.drop_index("ix_event_record_source_category", table_name="event_record")
    op.create_unique_constraint(
        op.f("uq_event_record_datetime"),
        "event_record",
        ["data_source_id", "start_datetime", "end_datetime"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_event_record_source_time"),
        "event_record",
        ["data_source_id", "start_datetime", "end_datetime"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_record_source_category"), "event_record", ["data_source_id", "category"], unique=False
    )
    op.drop_index(op.f("ix_device_type_priority_priority"), table_name="device_type_priority")
    op.create_index(op.f("idx_device_type_priority_order"), "device_type_priority", ["priority"], unique=False)
    op.drop_index("ix_data_source_user_provider", table_name="data_source")
    op.create_index(op.f("idx_data_source_user_provider"), "data_source", ["user_id", "provider"], unique=False)
    op.drop_index(op.f("ix_data_point_series_archive_bucket_start_at"), table_name="data_point_series_archive")
    # ### end Alembic commands ###
