"""data_source_model

Revision ID: e9a1db7428bf
Revises: 7a36d24b6c9c

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e9a1db7428bf"
down_revision: Union[str, None] = "7a36d24b6c9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_source",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("device_model", sa.String(length=100), nullable=True),
        sa.Column("software_version", sa.String(length=50), nullable=True),
        sa.Column("manufacturer", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "device_model", "source", name="uq_data_source_identity"),
    )
    op.create_index("idx_data_source_user", "data_source", ["user_id"], unique=False)
    op.create_index("idx_data_source_user_device", "data_source", ["user_id", "device_model"], unique=False)

    op.drop_constraint(
        op.f("data_point_series_external_device_mapping_id_fkey"), "data_point_series", type_="foreignkey"
    )
    op.drop_index(op.f("idx_data_point_series_mapping_type_time"), table_name="data_point_series")
    op.drop_constraint(op.f("uq_data_point_series_mapping_type_time"), "data_point_series", type_="unique")

    op.add_column("data_point_series", sa.Column("data_source_id", sa.UUID(), nullable=False))
    op.drop_column("data_point_series", "external_device_mapping_id")

    op.create_index(
        "idx_data_point_series_source_type_time",
        "data_point_series",
        ["data_source_id", "series_type_definition_id", "recorded_at"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_data_point_series_source_type_time",
        "data_point_series",
        ["data_source_id", "series_type_definition_id", "recorded_at"],
    )
    op.create_foreign_key(None, "data_point_series", "data_source", ["data_source_id"], ["id"], ondelete="CASCADE")

    op.drop_constraint(op.f("event_record_external_device_mapping_id_fkey"), "event_record", type_="foreignkey")
    op.drop_index(op.f("idx_event_record_mapping_category"), table_name="event_record")
    op.drop_index(op.f("idx_event_record_mapping_time"), table_name="event_record")
    op.drop_constraint(op.f("uq_event_record_datetime"), "event_record", type_="unique")

    op.add_column("event_record", sa.Column("data_source_id", sa.UUID(), nullable=False))
    op.drop_column("event_record", "external_device_mapping_id")

    op.create_unique_constraint(
        "uq_event_record_datetime", "event_record", ["data_source_id", "start_datetime", "end_datetime"]
    )
    op.create_index("idx_event_record_source_category", "event_record", ["data_source_id", "category"], unique=False)
    op.create_index(
        "idx_event_record_source_time",
        "event_record",
        ["data_source_id", "start_datetime", "end_datetime"],
        unique=False,
    )
    op.create_foreign_key(None, "event_record", "data_source", ["data_source_id"], ["id"], ondelete="CASCADE")

    op.drop_index(op.f("idx_external_mapping_device"), table_name="external_device_mapping")
    op.drop_index(op.f("idx_external_mapping_user"), table_name="external_device_mapping")
    op.drop_table("external_device_mapping")
    op.drop_table("device_software")
    op.drop_table("device")

    op.alter_column("user_connection", "access_token", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "user_connection", "token_expires_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_connection", "token_expires_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    op.alter_column("user_connection", "access_token", existing_type=sa.TEXT(), nullable=False)
    op.add_column(
        "event_record", sa.Column("external_device_mapping_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "event_record", type_="foreignkey")
    op.create_foreign_key(
        op.f("event_record_external_device_mapping_id_fkey"),
        "event_record",
        "external_device_mapping",
        ["external_device_mapping_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("idx_event_record_source_time", table_name="event_record")
    op.drop_index("idx_event_record_source_category", table_name="event_record")
    op.drop_constraint("uq_event_record_datetime", "event_record", type_="unique")
    op.create_unique_constraint(
        op.f("uq_event_record_datetime"),
        "event_record",
        ["external_device_mapping_id", "start_datetime", "end_datetime"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_event_record_mapping_time"),
        "event_record",
        ["external_device_mapping_id", "start_datetime", "end_datetime"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_record_mapping_category"),
        "event_record",
        ["external_device_mapping_id", "category"],
        unique=False,
    )
    op.drop_column("event_record", "data_source_id")
    op.add_column(
        "data_point_series", sa.Column("external_device_mapping_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "data_point_series", type_="foreignkey")
    op.create_foreign_key(
        op.f("data_point_series_external_device_mapping_id_fkey"),
        "data_point_series",
        "external_device_mapping",
        ["external_device_mapping_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_data_point_series_source_type_time", "data_point_series", type_="unique")
    op.drop_index("idx_data_point_series_source_type_time", table_name="data_point_series")
    op.create_unique_constraint(
        op.f("uq_data_point_series_mapping_type_time"),
        "data_point_series",
        ["external_device_mapping_id", "series_type_definition_id", "recorded_at"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_data_point_series_mapping_type_time"),
        "data_point_series",
        ["external_device_mapping_id", "series_type_definition_id", "recorded_at"],
        unique=False,
    )
    op.drop_column("data_point_series", "data_source_id")
    op.create_table(
        "device_software",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("device_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("version", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"], ["device.id"], name=op.f("device_software_device_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("device_software_pkey")),
    )
    op.create_table(
        "external_device_mapping",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("device_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("provider_name", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("external_device_mapping_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("external_device_mapping_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "provider_name",
            "device_id",
            name=op.f("uq_external_mapping_user_provider_device"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("idx_external_mapping_user"), "external_device_mapping", ["user_id"], unique=False)
    op.create_index(op.f("idx_external_mapping_device"), "external_device_mapping", ["device_id"], unique=False)
    op.create_table(
        "device",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("serial_number", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("provider_name", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("device_pkey")),
    )
    op.drop_index("idx_data_source_user_device", table_name="data_source")
    op.drop_index("idx_data_source_user", table_name="data_source")
    op.drop_table("data_source")
    # ### end Alembic commands ###
