"""priority

Revision ID: 0e8f0a9be2cc
Revises: e9a1db7428bf

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e8f0a9be2cc"
down_revision: Union[str, None] = "e9a1db7428bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_type_priority",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "device_type",
            sa.Enum("WATCH", "BAND", "PHONE", "SCALE", "RING", "OTHER", "UNKNOWN", name="devicetype"),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_type"),
    )
    op.create_index("idx_device_type_priority_order", "device_type_priority", ["priority"], unique=False)
    op.create_table(
        "provider_priority",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider"),
    )
    op.create_index("idx_provider_priority_order", "provider_priority", ["priority"], unique=False)
    op.add_column("data_source", sa.Column("provider", sa.String(length=50), nullable=False))
    op.add_column("data_source", sa.Column("user_connection_id", sa.UUID(), nullable=True))
    op.add_column("data_source", sa.Column("device_type", sa.String(length=32), nullable=True))
    op.add_column("data_source", sa.Column("original_source_name", sa.String(length=100), nullable=True))
    op.drop_index(op.f("idx_data_source_user"), table_name="data_source")
    op.drop_index(op.f("idx_data_source_user_device"), table_name="data_source")
    op.drop_constraint(op.f("uq_data_source_identity"), "data_source", type_="unique")
    op.create_index(
        "uq_data_source_identity",
        "data_source",
        [
            "user_id",
            "provider",
            sa.literal_column("COALESCE(device_model, '')"),
            sa.literal_column("COALESCE(source, '')"),
        ],
        unique=True,
    )
    op.create_index("idx_data_source_user_provider", "data_source", ["user_id", "provider"], unique=False)
    op.create_foreign_key(None, "data_source", "user_connection", ["user_connection_id"], ["id"], ondelete="SET NULL")
    op.drop_column("data_source", "manufacturer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_source", sa.Column("manufacturer", sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, "data_source", type_="foreignkey")
    op.drop_index("idx_data_source_user_provider", table_name="data_source")
    op.drop_index("uq_data_source_identity", table_name="data_source")
    op.create_unique_constraint(
        op.f("uq_data_source_identity"),
        "data_source",
        ["user_id", "device_model", "source"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_data_source_user_device"), "data_source", ["user_id", "device_model"], unique=False)
    op.create_index(op.f("idx_data_source_user"), "data_source", ["user_id"], unique=False)
    op.drop_column("data_source", "original_source_name")
    op.drop_column("data_source", "device_type")
    op.drop_column("data_source", "user_connection_id")
    op.drop_column("data_source", "provider")
    op.drop_index("idx_provider_priority_order", table_name="provider_priority")
    op.drop_table("provider_priority")
    op.drop_index("idx_device_type_priority_order", table_name="device_type_priority")
    op.drop_table("device_type_priority")
    # ### end Alembic commands ###
